sudo: required

language: java

services:
  - docker

before_install:
- docker pull qcifengineering/redbox-builder
- docker run -e "CLONEPATH=https://github.com/the-fascinator/the-fascinator.git" qcifengineering/redbox-builder

install: true

script: true
